[workspace]
members = [
  "agentd",
  "agentd-client",
  "agentd-events",
  "agentd-inference",
  "agentd-node",
  "agentd-sandbox",
  "agentd-telemetry",
]
resolver = "3"

[workspace.dependencies]
agentd-events = { path = "agentd-events" }
agentd-inference = { path = "agentd-inference" }
agentd-node = { path = "agentd-node" }
agentd-sandbox = { path = "agentd-sandbox" }
agentd-telemetry = { path = "agentd-telemetry" }
async-stream = "0.3"
async-trait = "0.1.89"
axum = { version = "0.8.9" }
base64 = "0.22"
clap = { version = "4.6.6" }
futures-util = { version = "0.3.34", features = ["sink"] }
opentelemetry = "0.32"
opentelemetry-otlp = { version = "0.32", default-features = false, features = [
  "http-proto",
  "reqwest-client",
  "reqwest-rustls",
  "trace",
] }
opentelemetry_sdk = { version = "0.32", features = [
  "experimental_trace_batch_span_processor_with_async_runtime",
  "rt-tokio",
] }
reqwest = { version = "0.12", default-features = false, features = [
  "json",
  "rustls-tls",
  "stream",
] }
rusqlite = { version = "0.40.2", features = ["bundled"] }
secrecy = { version = "0.10.3", features = ["serde"] }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = { version = "1.0.151" }
sha2 = "0.10.9"
thiserror = { version = "2.0.20" }
time = { version = "0.3.55", features = ["formatting", "parsing"] }
tokio = { version = "1.53.1" }
tokio-tungstenite = { version = "0.30.0", default-features = false, features = [
  "handshake",
] }
tower-http = { version = "0.7.1" }
tracing = { version = "0.1.44" }
tracing-opentelemetry = "0.33"
tracing-subscriber = { version = "0.3.23" }
uuid = { version = "1.26.1", features = ["v4", "v7"] }

[workspace.lints.clippy]
all = "deny"
expect_used = "deny"
nursery = "deny"
panic = "deny"
pedantic = "deny"
todo = "deny"
unimplemented = "deny"
unwrap_used = "deny"

[workspace.lints.rust]
future_incompatible = "deny"
unsafe_code = "deny"
unused = "deny"

[workspace.metadata.crane]
name = "agent"

[workspace.package]
edition = "2024"
version = "0.0.0"
