[package]
edition.workspace = true
name = "agentd"
version.workspace = true

[dependencies]
axum = { workspace = true, features = ["tracing"] }
clap = { workspace = true, features = ["derive"] }
thiserror = { workspace = true }
tokio = { workspace = true, features = [
  "macros",
  "net",
  "rt-multi-thread",
  "signal",
] }
tower-http = { workspace = true, features = ["trace"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter", "json"] }

[lints]
workspace = true

[dev-dependencies]
tempfile = "3.27.0"
