name: setup nix
description: Install Nix and restore the shared Nix store cache
runs:
  using: composite
  steps:
    - uses: DeterminateSystems/determinate-nix-action@8d87e8d5e5b8a8309d4281094560f127d9a265f1 # v3.22.5
    - uses: DeterminateSystems/flakehub-cache-action@main
