name: nix
on:
  pull_request:
  push:
    branches:
      - "main"
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-nix
  cancel-in-progress: true
permissions:
  id-token: write
  contents: read
jobs:
  DeterminateCI:
    uses: DeterminateSystems/ci/.github/workflows/workflow.yml@main
    permissions:
      id-token: write
      contents: read
